HandyTaxApp/Models/Invoice.cs
using System.ComponentModel.DataAnnotations;

namespace HandyTaxApp.Models
{
    public class Invoice
    {
        [Key]
        public int Id { get; set; }
        public int? InvoiceNumber { get; set; }
        public string InvoiceContractor { get; set; }
        public string? InvoiceContractorPostalCode { get; set; }
        public string? InvoiceContractorAddress { get; set; }
        public int InvoiceSum { get; set; }
        public int InvoiceSumVat { get; set; }
        public string InvoiceDescription { get; set; }
        public DateTime InvoiceDate { get; set; }
        public string? ImageURL { get; set; }
    }
}

HandyTaxApp/Controllers/InvoiceController.cs
using HandyTaxApp.Models;
using HandyTaxApp.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HandyTaxApp.Controllers
{
    [Authorize]
    public class InvoiceController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public InvoiceController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;   
        }
        public IActionResult Index()
        {
            IEnumerable<Invoice> ObjectInvoiceList = _unitOfWork.Invoices.GetAll();
            return View(ObjectInvoiceList);
        }

        public IActionResult DetailsPage(int? Id)
        {
            Invoice invoice = _unitOfWork.Invoices.GetFirstOrDefault(u => u.Id == Id);
            return View(invoice);  
        }

        public IActionResult UpsertPage(int? Id)
        {
            if (ModelState.IsValid)
            {     
                if (Id == 0 || Id == null)
                {
                    
                    Invoice invoice = new Invoice();
                    
                    return View(invoice);
                }
                else
                {
                    var InvoiceFromDb = _unitOfWork.Invoices.GetFirstOrDefault(u => u.Id == Id);
                    return View(InvoiceFromDb);
                }
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Invoice Object, IFormFile imgFile)
        {

            if (ModelState.IsValid)
            {
                string wwwwRootPath = _webHostEnvironment.WebRootPath;

                if(imgFile != null)
                {
                    string FileName = Guid.NewGuid().ToString();
                    var UploadImage = Path.Combine(wwwwRootPath, @"costInvoiceImages");
                    var Extension = Path.GetExtension(imgFile.FileName);

                    if(Object.ImageURL != null)
                    {
                        var oldImagePath = Path.Combine(wwwwRootPath, Object.ImageURL.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }

                    }

                    using (var fileStreamImage = new FileStream(Path.Combine(UploadImage, FileName + Extension), FileMode.Create))
                    {
                        imgFile.CopyTo(fileStreamImage);
                    }                  

                    Object.ImageURL = @"\costInvoiceImages\" + FileName + Extension;
                }
                

                if (Object.Id == 0)
                {
                    _unitOfWork.Invoices.Add(Object);
                }
                else
                {
                    _unitOfWork.Invoices.Update(Object);
                }
                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        public IActionResult DeletePage(int? Id)
        {
            Invoice invoice = _unitOfWork.Invoices.GetFirstOrDefault(u => u.Id == Id);
            return View(invoice);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Invoice Object, IFormFile imgFile)
        {
            string wwwwRootPath = _webHostEnvironment.WebRootPath;

            if (Object.ImageURL != null)
            {
                var oldImagePath = Path.Combine(wwwwRootPath, Object.ImageURL.TrimStart('\\'));
                if (System.IO.File.Exists(oldImagePath))
                {
                    System.IO.File.Delete(oldImagePath);
                }
            }
            _unitOfWork.Invoices.Remove(Object);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

HandyTaxApp/Controllers/OutcomeInvoiceController.cs
using HandyTaxApp.Models;
using HandyTaxApp.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace HandyTaxApp.Controllers
{
    [Authorize]
    public class OutcomeInvoiceController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public OutcomeInvoiceController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;   
        }

        public IActionResult Index()
        {
            IEnumerable<OutcomeInvoice> ObjectOutcomeInvoiceList = _unitOfWork.OutcomeInvoices.GetAll();
            return View(ObjectOutcomeInvoiceList);
        }

        public IActionResult DetailsPage(int? Id)
        {
            OutcomeInvoice outcomeinvoice = _unitOfWork.OutcomeInvoices.GetFirstOrDefault(u => u.Id == Id);
            return View(outcomeinvoice);  
        }

        public IActionResult UpsertPage(int? Id)
        {
            if (ModelState.IsValid)
            {     
                if (Id == 0 || Id == null)
                {

                    OutcomeInvoice outcomeinvoice = new OutcomeInvoice();
                    
                    return View(outcomeinvoice);
                }
                else
                {
                    var outcomeInvoiceFromDb = _unitOfWork.OutcomeInvoices.GetFirstOrDefault(u => u.Id == Id);
                    return View(outcomeInvoiceFromDb);
                }
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(OutcomeInvoice Object)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            Object.ApplicationUserId = claim.Value;

            //if (ModelState.IsValid)
            //{
                

                var totalAmount = Object.UnitPrice * Object.Quantity;
                Object.TotalAmount = totalAmount;

                var totalAmountVAT = (int)(totalAmount * 1.23);
                Object.TotalAmountVAT = totalAmountVAT;
                
                if (Object.Id == 0)
                {
                    _unitOfWork.OutcomeInvoices.Add(Object); 
                }
                else
                {
                    _unitOfWork.OutcomeInvoices.Update(Object);
                }
                _unitOfWork.Save();

                return RedirectToAction("Index");
            //}
            //return RedirectToAction("Index");
        }

        public IActionResult DeletePage(int? Id)
        {
            OutcomeInvoice outcomeinvoice = _unitOfWork.OutcomeInvoices.GetFirstOrDefault(u => u.Id == Id);
            return View(outcomeinvoice);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(OutcomeInvoice Object)
        {
            _unitOfWork.OutcomeInvoices.Remove(Object);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

HandyTaxApp/Views/Invoice/DeletePage.cshtml
@model Invoice;

@{
    ViewData["Title"] = "DeletePage";
}

<form method="post" asp-action="Delete" enctype="multipart/form-data">
    <input asp-for="Id" hidden/>
    <input asp-for="ImageURL" hidden/>
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Usun fakture</h2>
            <hr />
        </div>        

        <div class="row mb-3">
            <div class="col-12">
                    <button type="submit" class="btn btn-danger" style="width:100%">
                        <img src="/lib/bootstrap/icons/trash.svg" alt="Bootstrap" width="20" height="20">
                            Usun
                    </button>       
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-12">
                <a asp-controller="Invoice" asp-action="Index" class="btn btn-primary" style="width:100%">Take Me Back</a>
            </div>
        </div>
    </div>
</form>

                

HandyTaxApp/Views/Invoice/Index.cshtml
<!DOCTYPE html>
<html lang="en">
@model IEnumerable<Invoice>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../assets/img/favicon.png">
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
    <!-- Nucleo Icons -->
    <link href="../assets/css/nucleo-icons.css" rel="stylesheet" />
    <link href="../assets/css/nucleo-svg.css" rel="stylesheet" />
    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <!-- Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
    <!-- CSS Files -->
    <link id="pagestyle" href="../assets/css/material-dashboard.css?v=3.0.4" rel="stylesheet" />
</head>

<body class="g-sidenav-show  bg-gray-200">
    <aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark" id="sidenav-main">

        <div class="sidenav-header">
            <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
            <a class="navbar-brand m-0">
                <img src="~/img/logo.jpg" class="navbar-brand-img h-100" alt="main_logo">
                <span class="ms-1 font-weight-bold text-white">HandyTax App</span>
            </a>
        </div>


        <hr class="horizontal light mt-0 mb-2">

        <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
            <ul class="navbar-nav">

                <li class="nav-item">
                    <a class="nav-link text-white " asp-controller="Home" asp-action="Index">

                        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="material-icons opacity-10">dashboard</i>
                        </div>

                        <span class="nav-link-text ms-1">Pulpit</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-white " asp-controller="OutcomeInvoice" asp-action="Index">

                        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="material-icons opacity-10">table_view</i>
                        </div>

                        <span class="nav-link-text ms-1">Faktury</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-white " asp-controller="Invoice" asp-action="Index">

                        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="material-icons opacity-10">receipt_long</i>
                        </div>

                        <span class="nav-link-text ms-1">Koszty</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-white " asp-controller="" asp-action="">

                        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="material-icons opacity-10">view_in_ar</i>
                        </div>

                        <span class="nav-link-text ms-1">Formularze</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-white " asp-controller="" asp-action="">

                        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="material-icons opacity-10">notifications</i>
                        </div>

                        <span class="nav-link-text ms-1">Powiadomienia</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-white " asp-controller="" asp-action="">

                        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="material-icons opacity-10">person</i>
                        </div>

                        <span class="nav-link-text ms-1">Moj Profil</span>
                    </a>
                </li>
            </ul>
        </div>

    </aside>
    <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">

        <!-- Navbar -->
        <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
            <div class="container-fluid py-1 px-3">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
                        <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">HandyTax App</a></li>
                        <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Koszty</li>
                    </ol>
                </nav>
                <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
                    <div class="ms-md-auto pe-md-3 d-flex align-items-center">
                        <div class="input-group input-group-outline">
                            <label class="form-label">Type here...</label>
                            <input type="text" class="form-control">
                        </div>
                    </div>
                    <ul class="navbar-nav  justify-content-end">
                        <li class="nav-item d-flex align-items-center">
                            <a asp-controller="Invoice" asp-action="UpsertPage" class="btn btn-outline-primary btn-sm mb-0 me-3">Dodaj koszt</a>
                        </li>
                        <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
                            <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
                                <div class="sidenav-toggler-inner">
                                    <i class="sidenav-toggler-line"></i>
                                    <i class="sidenav-toggler-line"></i>
                                    <i class="sidenav-toggler-line"></i>
                                </div>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- End Navbar -->

        <div class="container-fluid py-4">
            <div class="row">
                <div class="col-12">
                    <div class="card my-4">
                        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                            <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                                <h6 class="text-white text-capitalize ps-3">Faktury kosztowe</h6>
                            </div>
                        </div>
                        <div class="card-body px-0 pb-2">
                            <div class="table-responsive p-0">
                                <table class="table align-items-center mb-0">
                                    <thead>
                                        <tr>
                                            <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Kontrahent</th>
                                            <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Nr faktury</th>
                                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Koszt netto</th>
                                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Rodzaj</th>
                                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Data</th>
                                            <th class="text-secondary opacity-7"></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var Object in Model)
                                        {
                                            <tr>
                                                <td>
                                                    <div class="d-flex px-2 py-1">
                                                        <div class="d-flex flex-column justify-content-center">
                                                            <h6 class="mb-0 text-sm">@Object.InvoiceContractor</h6>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td>
                                                    <p class="text-xs font-weight-bold mb-0">@Object.InvoiceNumber</p>
                                                </td>
                                                <td class="align-middle text-center text-sm">
                                                    <span class="text-secondary text-xs font-weight-bold">@Object.InvoiceSum</span>
                                                </td>
                                                <td class="align-middle text-center">
                                                    <span class="text-secondary text-xs font-weight-bold">@Object.InvoiceDescription</span>
                                                </td>
                                                <td class="align-middle text-center">
                                                    <span class="text-secondary text-xs font-weight-bold">@Object.InvoiceDate</span>
                                                </td>
                                                <td class="align-middle">
                                                    <a asp-controller="Invoice" asp-action="DetailsPage" asp-route-id="@Object.Id" class="badge badge-sm bg-gradient-success" data-toggle="tooltip" data-original-title="Edit user">
                                                        ...
                                                    </a>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <footer class="footer py-4  ">
                <div class="container-fluid">
                    <div class="row align-items-center justify-content-lg-between">
                        <div class="col-lg-6 mb-lg-0 mb-4">
                            <div class="copyright text-center text-sm text-muted text-lg-start">
                                © <script>
                                      document.write(new Date().getFullYear())
                                </script>,
                                Handy Tax
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <ul class="nav nav-footer justify-content-center justify-content-lg-end">
                                <li class="nav-item">
                                    <a asp-area="" asp-controller="Home" asp-action="Privacy_policy" class="nav-link text-muted" target="_blank">Polityka prywatności</a>
                                </li>
                                <li class="nav-item">
                                    <a asp-area="" asp-controller="Home" asp-action="Cookies" class="nav-link text-muted" target="_blank">Cookies</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </main>

    <!--   Core JS Files   -->
    <script src="../assets/js/core/popper.min.js"></script>
    <script src="../assets/js/core/bootstrap.min.js"></script>
    <script src="../assets/js/plugins/perfect-scrollbar.min.js"></script>
    <script src="../assets/js/plugins/smooth-scrollbar.min.js"></script>
    <script>
        var win = navigator.platform.indexOf('Win') > -1;
        if (win && document.querySelector('#sidenav-scrollbar')) {
            var options = {
                damping: '0.5'
            }
            Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
        }
    </script>
    <!-- Github buttons -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="../assets/js/material-dashboard.min.js?v=3.0.4"></script>
</body>
</html>